### ISSUE TITLE
url fix

### ISSUE THREAD

**Issue by lee-sj** [awskrug/awskrug.github.io#1]
awskrug 사이트 확인중 변경된 url 이 있는것 같아 이슈 남깁니다. 
이슈 규정이 따로 없는것 같아서 그냥 남깁니다. 
판교 그룹 url 변경필요합니다. 
Pankyo -> Pangyo

**Comment by channy** [comment]
thanks! fixed in https://github.com/awskrug/awskrug.github.io/commit/390101aae6e4a86f711dc9e0fb9d58bcd4f7b499
